#!/bin/bash
# Make noninteractive
export DEBIAN_FRONTEND=noninteractive

# install apache webserver and PHP
apt-get install -y libapache2-mod-php5 apache2

# Delete default page
rm -r /var/www/html/*

# Move script and letters to webserver directory
mv $CONTENT_DIR/*.php /var/www/html
mv $CONTENT_DIR/letters /var/www/html
